libraryproject/libraryapp/urls.py
from django.urls import include, path
from .views import *

app_name = "libraryapp"

urlpatterns = [
    path('', home, name='home'),
    path('libraries/', list_libraries, name='libraries'),
    path('library/form', library_form, name='library_form'),
    path('libraries/<int:library_id>/', library_details, name='library'),
    path('books/', book_list, name='books'),
    path('book/form', book_form, name='book_form'),
    path('books/<int:book_id>/', book_details, name='book'),
    path('books/<int:book_id>/form/', book_edit_form, name='book_edit_form'),
    path('librarians/', list_librarians, name='librarians'),
    path('librarians/<int:librarian_id>/', librarian_details, name='librarian'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', logout_user, name='logout'),
]

libraryproject/libraryproject/urls.py
from django.contrib import admin
from django.urls import include, path
from libraryapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libraryapp.urls')),
]

libraryproject/libraryapp/models/book.py
from .library import Library
from .librarian import Librarian
from django.db import models
from django.urls import reverse

class Book (models.Model):
    title = models.CharField(max_length=50)
    isbn = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    publisher = models.CharField(max_length=50)
    year_published = models.IntegerField()
    library = models.ForeignKey(Library, on_delete=models.CASCADE)
    librarian = models.ForeignKey(Librarian, on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("book")
        verbose_name_plural = ("books")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})

libraryproject/libraryapp/models/librarian.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from .library import Library


class Librarian(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    library = models.ForeignKey(
        Library, related_name="librarians",
        null=True, # Makes column nullable in DB
        blank=True, # Allows blank value on objects
        on_delete=models.CASCADE)


# These receiver hooks allow you to continue to
# work with the `User` class in your Python code.


# Every time a `User` is created, a matching `Librarian`
# object will be created and attached as a one-to-one property
@receiver(post_save, sender=User)
def create_librarian(sender, instance, created, **kwargs):
    if created:
        Librarian.objects.create(user=instance)

# Every time a `User` is saved, its matching `Librarian`
# object will be saved.
@receiver(post_save, sender=User)
def save_librarian(sender, instance, **kwargs):
    instance.librarian.save()

libraryproject/libraryapp/models/library.py
from django.db import models
from django.urls import reverse

class Library (models.Model):

    name = models.CharField(max_length=50)
    address = models.CharField(max_length=50)

    class Meta:
        verbose_name = ("library")
        verbose_name_plural = ("libraries")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("library_detail", kwargs={"pk": self.pk})

libraryproject/libraryapp/models/modelfactory.py
import sqlite3

# Higher order function to create instances of models
# when performing single table queries
def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

libraryproject/libraryapp/views.py
sfrom django.shortcuts import render

# Create your views here.

libraryproject/libraryapp/views/connection.py
class Connection:
    db_path = "/Users/landonmorgan/workspace/backend/library-management/libraryproject/db.sqlite3"

libraryproject/libraryapp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

libraryproject/libraryapp/templates/books/detail.html
{% extends 'shared/base.html' %}
    {% block content %}
      <section id="book-details">
          <h1>{{ book.title }}</h1>
          <h3>By {{ book.author }}</h3>
          <div>Published in {{ book.year_published }} by {{ book.publisher }}</div>
          <div>ISBN: {{ book.isbn }}</div>
              <div>Located in the {{ book.library.name }}</div>
              <div>Registered by {{ book.librarian.first_name }} {{ book.librarian.last_name }}</div>
      </section>

      <section id="book-actions" style="display:flex;">
          <form action="{% url 'libraryapp:book' book.id %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="actual_method" value="DELETE">
              <button>Delete</button>
          </form>
          <form action="{% url 'libraryapp:book_edit_form' book.id %}" method="GET">
              {% csrf_token %}
              <button>Edit</button>
          </form>
      </section>
    {% endblock %}

libraryproject/libraryapp/templates/books/form.html
{% extends 'shared/base.html' %}
    {% block content %}
      <h1>Inventory Book</h1>
      {% if book.id is not None %}
          <form action="{% url 'libraryapp:book' book.id %}" method="post">
      {% else %}
          <form action="{% url 'libraryapp:books' %}" method="post">
      {% endif %}
          {% csrf_token %}
        <fieldset>
            <label for="title">Title: </label>
            <input id="title" type="text" name="title" value="{{book.title}}">
        </fieldset>
        <fieldset>
            <label for="author">Author: </label>
            <input id="author" type="text" name="author" value="{{book.author}}">
        </fieldset>
        <fieldset>
            <label for="publisher">Publisher: </label>
            <input id="publisher" type="text" name="publisher" value="{{book.publisher}}">
        </fieldset>
        <fieldset>
            <label for="year_published">Year of publication: </label>
            <input id="year_published" type="number" name="year_published" value="{{book.year_published}}">
        </fieldset>
        <fieldset>
            <label for="isbn">ISBN: </label>
            <input id="isbn" type="text" name="isbn" value="{{book.isbn}}">
        </fieldset>
        <fieldset>
            <label for="library">Library: </label>
            <select id="library" type="text" name="library">
                  {% for library in all_libraries %}
                      <option value="{{ library.id }}" 
                      {% if book.library_id == library.id %}
                        selected
                      {% endif %}
                      >{{ library.name }}</option>
                  {% endfor %}
            </select>
        </fieldset>
        {% if book.id is not None %}
          <input type="hidden" name="actual_method" value="PUT">
          <input type="submit" value="Update" />
        {% else %}
          <input type="submit" value="Create" />
        {% endif %}
      </form>
    {% endblock %}

libraryproject/libraryapp/templates/books/list.html
{% extends 'shared/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/books.css' %}" />
{% endblock %}

{% block content %}
    <h1>Books</h1>

    <dialog class="infoDialog">
      <div class="infoDialog__message"></div>
      <button class="closeDialog">Close</button>
    </dialog>

    <a href="{% url 'libraryapp:book_form' %}">Add Book to Inventory</a>

    <ol class="books">
    {% for book in all_books %}
        <li class="book">
            <a class="book__title" href="{% url 'libraryapp:book' book.id %}"> {{ book.title }}</a>
            <div class="book__description">
                by {{book.author}} published in {{book.year_published}}
            </div>
            <button id="detail--{{ book.id }}">Details</button>
        </li>
    {% endfor %}
    </ol>
{% endblock %}
{% block scripts %}
    <script src="{% static 'scripts/books.js' %}"></script>
{% endblock %}

libraryproject/libraryapp/templates/home.html
{% extends 'shared/base.html' %}
{% block content %}
    <h1>Welcome to the Nashville Library Management System</h1>
{% endblock %}

libraryproject/libraryapp/templates/librarians/detail.html
{% extends 'shared/base.html' %}
{% block content %}
    <h1>{{ librarian.first_name }} {{ librarian.last_name }}</h1>
    <p><b>Library: </b>{{ librarian.name }} {{ librarian.address }}</p>
{% endblock %}

libraryproject/libraryapp/templates/librarians/list.html
{% extends 'shared/base.html' %}
{% block content %}
    <h1>Librarians</h1>

    <ol>
    {% for librarian in all_librarians %}
        <li>
          <a href="{% url 'libraryapp:librarian' librarian.id %}"> {{ librarian.first_name }} {{ librarian.last_name }}</a>
        </li>
    {% endfor %}
    </ol>
{% endblock %}

libraryproject/libraryapp/templates/libraries/detail.html
{% extends 'shared/base.html' %}
{% block content %}
    <h1>{{ library.name }}</h1>
    <h2>Address: {{ library.address }}</h2>
{% endblock %}

libraryproject/libraryapp/templates/libraries/form.html
{% extends 'shared/base.html' %}
{% block content %}
    <h1>Create Library</h1>
    <form action="{% url 'libraryapp:libraries' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="name">Name: </label>
          <input id="name" type="text" name="name">
      </fieldset>
      <fieldset>
          <label for="address">Address: </label>
          <input id="address" type="text" name="address">
      </fieldset>
      <input type="submit" value="CREATE" />
    </form>
{% endblock %}

libraryproject/libraryapp/templates/libraries/list.html
{% extends 'shared/base.html' %}
{% block content %}
    <h1>Libraries</h1>
    <a href="{% url 'libraryapp:library_form' %}">Add Library</a>
    <ol>
    {% for library in all_libraries %}
        <li>
            <a href="{% url 'libraryapp:library' library.id %}">{{ library.name }}</a>
            ({{ library.address }})
            <ul>
            {% for book in library.books %}
                <li>{{ book.title }}</li>
            {% endfor %}
            </ul>
        </li>
    {% endfor %}
    </ol>
{% endblock %}

libraryproject/libraryapp/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Library</title>

    <link rel="stylesheet" href="{% static 'styles/base.css' %}" />

    {% block css %}
    {% endblock %}
</head>

<body>

    <nav id="site-nav">
        <ol class="navList">
            <li class="navList__route"><a href="{% url 'libraryapp:home' %}">Home</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:libraries' %}">Libraries</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:books' %}">Books</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:librarians' %}">Librarians</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:logout' %}">Logout</a></li>
        </ol>
    </nav>

    <main class="main-content">
        {% block content %}
        {% endblock %}
    </main>

    {% block scripts %}
    {% endblock scripts %}
</body>

</html>